version: "3.8"

services:
  qdrant-0:
    container_name: qdrant-0
    image: qdrant/qdrant:v1.6.1
    entrypoint: ./entrypoint.sh
    # command: --bootstrap 'http://localhost:6335'
    command: --uri 'http://localhost:6335'
    volumes:
      - ./volumes/0/qdrant_storage:/qdrant/storage
      - ./volumes/0/qdrant_snapshots:/qdrant/snapshots
      - ./qdrant-config.yaml:/qdrant/config/production.yaml
    ports:
      - "6333:6333"
      - "6334:6334"
      - "6335:6335"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 2G