name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      qdrant:
        image: qdrant/qdrant:v1.6.1
        ports:
          - "6333:6333"
          - "6334:6334"
          - "6335:6335"
        volumes:
          - ./volumes/0/qdrant_storage:/qdrant/storage
          - ./volumes/0/qdrant_snapshots:/qdrant/snapshots
          - ./qdrant-config.yaml:/qdrant/config/production.yaml

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    # - name: Run Qdrant image
    #   run: docker compose up -d
    # - name: Install dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install libmemcached-dev memcached
    # - name: Start memcached daemons
    #   run: |
    #     memcached -d -p 11211
    # - name: Add memcached host to /etc/hosts
    #   run: |
    #     echo "127.0.0.1 memcached" | sudo tee -a /etc/hosts
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
