name: Run Test Template

on:
  workflow_call:
    inputs:
      qdrant_image:
        description: 'Qdrant Docker image to use'
        required: true
        type: string
      qdrant_version:
        description: 'Qdrant version'
        required: true
        type: string

jobs:
  build_test:
    runs-on: ubuntu-latest
    services:
      qdrant:
        image: ${{ inputs.qdrant_image }}
        ports:
          - "6333:6333"
          - "6334:6334"
          - "6335:6335"

    env:
        CI: true
        QDRANT_VERSION: ${{ inputs.qdrant_version }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Set version to the environment variable test
      run: echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
    
    - name: Get version from the environment variable test
      run: echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}"

    - name: Display current qdrant version and image
      run: |
        echo "Running with Qdrant image: ${{ inputs.qdrant_image }}"
        echo "Qdrant version: ${{ inputs.qdrant_version }}"

    # - name: Build
    #   run: dotnet build --configuration Release --no-restore
    
    # - name: Test
    #   run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Test
      run: dotnet test --configuration Release --verbosity normal
